apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdeliverymanagement
  labels:
    app: orderdeliverymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdeliverymanagement
  template:
    metadata:
      labels:
        app: orderdeliverymanagement
    spec:
      containers:
        - name: orderdeliverymanagement
          image: skcc12acr.azurecr.io/orderdeliverymanagement:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
